### PR TITLE
Add array helpers for PBXObjectReference

### PR DESCRIPTION
**Pull request by yonaskolb**
This just adds some extensions on Array to make the conversion between objects and references easier

### CODE REVIEW

**Comment by yonaskolb** [comment]
Thanks for the merge! I'm not pushing from a fork though, I'm still a maintainer of xcodeproj 😄

**Comment by yonaskolb** [comment]
I can't work out what happened to these commits. Did they get erased in a rebase?

**Comment by pepibumur** [comment]
Did they? I just merged using GitHub's button. Would you mind pushing and merging them yourself?

**Comment by yonaskolb** [comment]
Yeah sure. It's just a bit scary. If these got lost, then maybe something else got lost

**Pull request merged**
