### PR TITLE
Avoid warning target name has different case

### PR DESCRIPTION
**Pull request by giginet**
# Short description 📝

Latest Swift toolchain raises the following error.

```console
$ swift build
Fetching https://github.com/kylef/Spectre.git
Fetching https://github.com/kylef/PathKit
Fetching https://github.com/tadija/AEXML
Fetching https://github.com/tuist/Shell
Completed resolution in 3.60s
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.9.0
Cloning https://github.com/tadija/AEXML
Resolving https://github.com/tadija/AEXML at 4.4.0
Cloning https://github.com/kylef/PathKit
Resolving https://github.com/kylef/PathKit at 1.0.0
Cloning https://github.com/tuist/Shell
Resolving https://github.com/tuist/Shell at 2.0.1
'XcodeProj' /Users/giginet/work/Swift/XcodeProj: warning: the target name XcodeProj has different case on the filesystem and the Package.swift manifest file
'XcodeProj' /Users/giginet/work/Swift/XcodeProj: warning: the target name XcodeProjTests has different case on the filesystem and the Package.swift manifest file
[8/27] Merging module PathKit
[8/34] Merging module PathKit% 
```

### Solution 📦

It causes because why Sources/Tests package directories are named with wrong cases.
They should be `XcodeProj` and `XcodeProjTests`.

### Implementation 👩‍💻👨‍💻

I rename package directories.
Replace all occurrences of paths

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
Please fix these files also 🙏 

- [ ] https://github.com/tuist/XcodeProj/blob/master/.swiftlint.yaml
- [ ] https://github.com/tuist/XcodeProj/blob/master/.jazzy.yaml
- [ ] https://github.com/tuist/XcodeProj/blob/master/.gitignore

**Comment by pepibumur** [comment]
We can merge after @kateinoigakukun 's suggestion is addressed. Thanks for tackling this @giginet

**Comment by giginet** [comment]
@kateinoigakukun @pepibumur Good catch!

Should I also modify here? https://github.com/tuist/XcodeProj/blob/master/.jazzy.yaml#L2

**Comment by pepibumur** [comment]
Yes

**Comment by giginet** [comment]
Fixed

**Pull request merged**
