### PR TITLE
Include project name/path into "Products" group ID generation logic 

### PR DESCRIPTION
**Pull request by damirdavletov**
Resolves https://github.com/tuist/XcodeProj/issues/538

### Short description 📝
Add referenced project name or path whichever is available to the permanent "Products" group ID generation logic.

### Solution 📦
The solution doesn't break the reproducibility of permanent ID generation and produces different ID for each added referenced project

### CODE REVIEW

**Comment by damirdavletov** [comment]
I am not sure why Changelog fails, please let me know if anything needs fixing.

**Comment by damirdavletov** [comment]
Thanks @pepibumur ! Changelog is updated please check.

**Comment by pepibumur** [comment]
😅Would you mind solving the conflicts @damirdavletov? We can merge afterward.

**Comment by damirdavletov** [comment]
@pepibumur Done!

**Comment by damirdavletov** [comment]
Hi @pepibumur! Would you help me getting this PR merged? Do I need to do anything else?

**Comment by pepibumur** [comment]
Sure! I forgot about this PR completely. Thanks for the reminder :)

**Comment by damirdavletov** [comment]
Thanks @pepibumur ! Nice gif! 😊

**Pull request merged**
