### PR TITLE
docs: Add try-catch to getting started

### PR DESCRIPTION
**Pull request by AlexKobachiJP**
Not sure if this was left out on purpose to keep the sample as small as possible but I feel that a getting started document should show code that builds without requiring fixes, even if it is as simple as adding a `try` statement, because it otherwise makes the documentation look sloppy.

(Apologies for not creating an issue first.)

### CODE REVIEW

**Review by kwridan — APPROVED** [review]
Thanks for contributing this @AlexKobachiJP 

Agreed, making the docs closer to reality is needed. At the very least `try ...` incase someone does copy and paste the snippet. 👍

**Comment by kwridan** [comment]
https://github.com/all-contributors add @AlexKobachiJP for docs

**Comment by kwridan** [comment]
@all-contributors add @AlexKobachiJP for docs

**Comment by AlexKobachiJP** [comment]
Thanks!

**Pull request merged**
