### PR TITLE
Sorting XML attributes

### PR DESCRIPTION
**Pull request by drekka**
Found that every times I saved a test project, that the order of the attributes in the schemes were changing. This resulted in Git thinking the files had changed when in fact they hadn't as the attribute values were the same. 

This PR sorts the XML attributes when writing XML files. This ensures that (after the first time), the attributes will always be in the same order and therefore the file will not be seen as changed unless an actual value changes.

### CODE REVIEW

**Comment by yonaskolb** [comment]
This could potentially fix #322. It needs to be tested though to see if Xcode rewrites the order when the schemes are edited.

**Comment by drekka** [comment]
Probably as Xcode doesn't seem to care about order. The problem with this was using a dictionary. The order was pretty much changing every time it was written even though the values were the same, so Git saw a lot of false updates so to speak. 

If Xcode changes some values in the scheme then it doesn't matter if it's sorted.

**Comment by pepibumur** [comment]
Thanks for fixing this @drekka. Did you check if Xcode follows the same sorting logic? If so, I think this is ready to be merged. I was thinking about adding an integration test that fails if Xcode changes that logic at any time, but I doubt Xcode will introduce such change because it'd cause a large git diff.

**Comment by drekka** [comment]
Thanks for the feedback guys. I went back into the code and realised the problem was actually not from being unsorted. But due to the BuildAction not being specified in the `attributesOrder` at the top of the extension. I removed my sort code and added BuildAction to the `attributesOrder` with its attributes in the order that Apple uses. Then updated the tests to match.

**Comment by yonaskolb** [comment]
Great! Perhaps it's still good to have sorted keys as a fallback. Then if new properties emerge, at least they will get deterministic sorting

**Pull request merged**
