### PR TITLE
Use safer dictionary

### PR DESCRIPTION
**Pull request by toshi0383**
Resolves https://github.com/tuist/xcodeproj/issues/426

### CODE REVIEW

**Comment by pepibumur** [comment]
Hey @toshi0383, thanks for fixing this. Two more things before we merge this PR:
- I'd add a test that passes through that code to verify that a build phase can be parsed even if it contains duplicated files.
- I'd update the CHANGELOG adding a new entry to the fixed section.

After that, we can merge the PR.

**Comment by toshi0383** [comment]
Done👌 Thanks for review!
Also rebased to master.

**Comment by toshi0383** [comment]
Oops sorry the test is failing. Working on it..

**Comment by toshi0383** [comment]
Should be good now.

**Pull request merged**
