### PR TITLE
Fix Xcode 13 build

### PR DESCRIPTION
**Pull request by raptorxcz**
Revert changes in #643.

Also adds Xcode 13 to workflows

### CODE REVIEW

**Review by yonaskolb — APPROVED** [review]
Looks good, assuming builds pass. Thanks!

**Comment by CognitiveDisson** [comment]
Can we bump the version after that?

**Comment by yonaskolb** [comment]
@fortmarek @pepibumur

**Review by fortmarek — APPROVED** [review]
Thanks, I'll create a patch release

**Pull request merged**
