### PR TITLE
Add ability to initialize scheme without a blueprint identifier

### LINKED ISSUE #509: Newly Generated Projects creates XCScheme without a BlueprintIdentifier
I am making a build file in swift to replace my Rakefile but as the subject says a newly generated xcodeproj creates schemes files

I made a simply change in 
XCScheme+BuildableReference.swift
```            
           if let blueprintIdentifier = element.attributes["BlueprintIdentifier"]  { 
//                throw XCSchemeError.missing(property: "BlueprintIdentifier")
                blueprint = .string(blueprintIdentifier)
            } else {
                blueprint = .string("")
            }
```

it all works fine. 

The aim was to add `environmentVariables` for the development

### PR DESCRIPTION
**Pull request by daltonclaybrook**
Resolves #509 

### Short description 📝
This PR fixes an issue where some schemes cannot be deserialized because a buildable reference does not contain a blueprint identifier.

### Solution 📦
The solution is to make the `blueprint` field optional on `BuildableReference`. The other option I considered was adding a new case to `Blueprint` called `.none`, but I felt simply making the property optional would be more ergonomic.

### CODE REVIEW

**Comment by daltonclaybrook** [comment]
Is anyone available to take a look at this? (cc: @pepibumur)

**Review by kwridan — COMMENTED** [review]
Thanks for submitting this @daltonclaybrook 

The changes look good, I have some small observations.

- `swift package generate-xcodeproj` does indeed generate schemes without the blueprint identifier, though Xcode overwrites those schemes to include them when viewing them in the scheme editor. At least with this change, those generated projects and schemes can be parsed correctly.
- This is a slightly breaking change and will need to mark it such in the `CHANGELOG.md` or perhaps it may need to be part of a major release - @pepibumur thoughts?
    - _Example: XcodeGen relies on the public `blueprintIdentifier` change [here](https://github.com/yonaskolb/XcodeGen/blob/master/Tests/XcodeGenKitTests/SchemeGeneratorTests.swift#L220)_

**Comment by daltonclaybrook** [comment]
Any action items on my end to get this moving? (cc: @kwridan @pepibumur)

**Review by pepibumur — APPROVED** [review]
Hey @daltonclaybrook 👋🏼 
I propose that we update the CHANGELOG.md with your changes, and flag them as breaking. I'll release a major version of XcodeProj once this is merged.

**Comment by kwridan** [comment]
Thanks @pepibumur! will submit a fix for https://github.com/tuist/tuist/issues/2991 first thing tomorrow as it's similar in breaking nature which can be bundled in the same major release.

**Review by kwridan — APPROVED** [review]

**Comment by kwridan** [comment]
@daltonclaybrook mind rebase / merging latest main with an updated change log?

**Comment by daltonclaybrook** [comment]
@kwridan yep, I'll be able to take care of that later this morning.

**Pull request merged**
