### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by pepibumur**
### Short description 📝
Add Linux support to xcodeproj.

### Implementation 👩‍💻👨‍💻
- [x] Add new build to the CircleCI pipeline that runs the build and tests on Ubuntu 16.04.
- [ ] Fix issues.

### CODE REVIEW

**Comment by pepibumur** [comment]
Still the same PropertyListDecoder issue:
image

@Keith I remember you asking something about this on Twitter. Could you figure out anything?

**Comment by pepibumur** [comment]
I found it https://bugs.swift.org/browse/SR-8259

**Comment by keith** [comment]
Yea I haven't tried to debug this one anymore. I'm not sure if it isn't built somehow, or just isn't bundled.

**Comment by pepibumur** [comment]
Closing this for now. I gave it another try unsuccessfully but the compiler raises some errors that are not easy to debug. If any user has a use case for using this library in linux, we can give it another shot in the future.

**Pull request closed without merging**
