### PR TITLE
Update AEXML v4.6.1

### PR DESCRIPTION
**Pull request by nnsnodnb**
Resolves ~~https://github.com/tuist/xcodeproj/issues/YYY~~

### Short description 📝

Update AEXML version to v4.6.1

### Solution 📦

I fixed XML's newline escaping.  
https://github.com/tadija/AEXML/pull/177

### Implementation 👩‍💻👨‍💻

- [x] Step 1 Fork -> Clone
- [x] Step 2 Executed `open Package.swift`
- [x] Step 3 Updated `AEXML` version in `xcodeproj.podspec` , `Cartfile` , `Carffile.resolved` & `Package.swift`

### CODE REVIEW

**Comment by nnsnodnb** [comment]
Hi.  
Is it possible to remove `.swift-version` from this repository?  
Then, I was able to resolve dependencies in my environment.

**Comment by pepibumur** [comment]
@all-contributors add @nnsnodnb for code

**Comment by pepibumur** [comment]
Thanks a lot for helping with this @nnsnodnb. If CI is green I'll merge the PR.

**Comment by fortmarek** [comment]
This seems like it has broken the checks, it's probably worth some investigation.

**Pull request merged**
