### PR TITLE
Extend list of known file extensions

### PR DESCRIPTION
**Pull request by dflems**
### Short description 📝
This PR adds more identifiers for extensions that Xcode can understand.

### Solution 📦
Xcode understands far more filetypes than the 36 listed here in this file. The "type" dropdown in Xcode is very long and contains many entries that were not enumerated in `XcodeProj`. Vendored into Xcode are a number of `.xcspec` files that define the relationships between file extensions and their type identifier.

### Implementation 👩‍💻👨‍💻
The extensions are derived from the following files in `Xcode3Core.ideplugin`

- `DevToolsCore.framework/Versions/A/Resources/BuiltInFileTypes.xcspec`
- `DevToolsCore.framework/Versions/A/Resources/StandardFileTypes.xcspec`
- `Core Data.xcplugin/Contents/Resources/Core Data.pbfilespec`
- `CoreBuildTasks.xcplugin/Contents/Resources/InstrumentsPackage.xcspec`
- `Intents.xcplugin/Contents/Resources/Intents.pbfilespec`
- `Metal.xcplugin/Contents/Resources/FileTypes.xcspec`
- `RCBuildSystemSupport.xcplugin/Contents/Resources/RCFileTypes.pbfilespec`
- `SceneKit.xcplugin/Contents/Resources/SceneKit FileTypes.xcspec`
- `SpriteKit.xcplugin/Contents/Resources/SpriteKitFileTypes.xcspec`
- `XCLanguageSupport.xcplugin/Contents/Resources/Swift.pbfilespec`

These `.xcspec` files are in ASCII plist format and contain entries that look like:

```
    {
        Type = FileType;
        Identifier = sourcecode.cpp.h;
        BasedOn = sourcecode.cpp;
        Extensions = (hp, hpp, hxx, "h++", H, "pch++", hh, ipp);
        AppliesToBuildRules = no;
        IncludeInIndex = NO;
        CanSetIncludeInIndex = NO;
        UTI = "public.c-plus-plus-header";
    },
```

Many of these entries include `Extensions`. These are file extensions that map to the `Identifier` in the same structure.

Similar mappings exist in [buck](https://github.com/facebook/buck/blob/930f1009d47e11fd6b88d465953d666f02da4fa4/src/com/facebook/buck/apple/xcode/xcodeproj/FileTypes.java#L31-L244) and [bazel](https://github.com/bazelbuild/tulsi/blob/7275338c1194d12fe0a80fb3b27322d70c84f3ac/src/TulsiGenerator/PBXUniformTypeIdentifiers.swift#L20-L217).

@pepibumur

### CODE REVIEW

**Comment by yonaskolb** [comment]
Nice work @dflems! Do you have a script that generated these values? If so might be nice to include in the repo

**Comment by pepibumur** [comment]
> Nice work @dflems! Do you have a script that generated these values? If so might be nice to include in the repo, even if the output needs some massaging before being added to the swift file

Yeah, that'd be great. Unless you wrote that list by hand :trollface:. Would you mind updating the CHANGELOG?

**Comment by dflems** [comment]
@pepibumur @yonaskolb: Added changelog and committed the script I used to generate these values. Pass in a path to `Xcode.app` and it will write JSON to stdout with a mapping of all the extensions.

**Comment by dflems** [comment]
@pepibumur: any chance you could cut a release with this in it? 🙏

**Comment by pepibumur** [comment]
[Here](https://github.com/tuist/XcodeProj/releases/tag/7.4.0) you go.

**Pull request merged**
